#-------------------------------
# Collections
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: false
    permalink: /blog/:slug
  works:
    output: false
    permalink: /work/:slug

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "works"
    values:
      layout: "work"
