# Collections
collections:
  pages:
    output: true
    permalink: /:name

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# SASS configuration
sass:
  style: compressed