# _config.yml
#-------------------------------
# Collections
collections:
  pages:
    output: true
    permalink: /:name

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
