# _data/settings.yml
title: Geoffrey Sperl
description: ELA and ESL educator focused on student-centered learning and digital literacy
color_scheme: light

author: Geoffrey Sperl
author__name: Geoffrey Sperl

menu__settings:
  menu__items:
    - title: 'About Me'
      url: '/'
    - title: 'Teaching'
      url: '/teaching/'
      submenu:
      - url: '/teaching/philosophy/'
        title: 'Teaching Philosophy'
      - url: '/teaching/research/'
        title: 'Research & Innovation'
    - title: 'Student Work'
      url: '/student-work/'
      submenu:
      - url: '/student-work/roleplaying-literacy/'
        title: 'Roleplaying & Literacy'
      - url: '/student-work/visual-thinking/'
        title: 'Visual & Analytical Thinking'
      - url: '/student-work/gaming-club/'
        title: 'Gaming Club'
    - title: 'Resources'
      submenu:
      - url: 'https://www.teacherspayteachers.com/Store/Geoffrey-Sperl'
        title: 'My TpT Store'
      - url: 'https://www.amazon.com/hz/wishlist/ls/30IV6MDWMC02O?ref_=wl_share'
        title: 'Amazon Wishlist'
      - url: 'https://bookshop.org/wishlists/e8d78e322424d0acfc4c2813ffafecbf335b9c57'
        title: 'Bookshop Wishlist'
    - title: 'Contact'
      submenu:
      - url: 'mailto:geoffrey@geoffreysperl.com'
        title: 'Email Me'
      - url: 'https://www.linkedin.com/in/geoffreysperl/'
        title: 'LinkedIn'