#-------------------------------
# Site Settings
title: Geoffrey Sperl
# logo: 
description: Geoffrey Sperl's Teaching Portfolio
color_scheme: auto # auto, light, or dark

#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'About Me'
      url: '/about/'
    - title: 'Effective Urban Educator'
      submenu:
      - url: '/reflective/'
        title: 'Reflective Practitioner'
      - url: '/innovative/'
        title: 'Innovative Practitioner'
      - url: '/equitable/'
        title: 'Committed to Equity for Diverse Learners'
    - title: 'Email Me'
      url: 'mailto:geoffrey@wayne.edu'

#-------------------------------
# Author Settings
author:
  author__name: Geoffrey Sperl
  # author__bio: I'm a student, teacher, and writer. My primary content area is ELA, but I also teach ESL and have 25 years working with computers.
  # author__avatar: '/images/geoffrey-sperl.jpg'

social:
- {icon: "ion-logo-linkedin", link: "https://linkedin.com/in/geoffreysperl"}
- {icon: "ion-logo-github", link: "https://github.com/geoffreysperl"}
- {icon: "ion-logo-send", link: "mailto:geoffrey@geoffreysperl.com"}
- {icon: "ion-logo-globe", link: "https://geoffreysperl.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero__title: Hi! I'm Geoffrey.
  hero__description: I'm an aspiring secondary ELA and ESL educator with a passion for teaching and learning. To read more about me, click "About Me" above. To contact me, click "Email Me" above.
  hero__image: "/images/geoffrey-sperl.jpg"