title: Geoffrey Sperl
description: Geoffrey Sperl's Teaching Portfolio
color_scheme: auto # auto, light, or dark

author: Geoffrey Sperl
author__name: Geoffrey Sperl

menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'About Me'
      url: '/about/'
    - title: 'Effective Urban Educator'
      submenu:
      - url: '/reflective/'
        title: 'Reflective Practitioner'
      - url: '/innovative/'
        title: 'Innovative Practitioner'
      - url: '/equitable/'
        title: 'Committed to Equity for Diverse Learners'
    - title: 'Contact Me'
      submenu:
      - url: 'mailto:geoffrey@wayne.edu'
        title: 'Email'
      - url: 'https://www.linkedin.com/in/geoffreysperl/'
        title: 'LinkedIn'

hero:
  enable: true
  hero__title: Hi! I'm Geoffrey.
  hero__description: I'm an emerging secondary ELA and ESL educator with a passion for teaching and learning. To read more about me, click "About Me" above. To get in touch, click "Contact Me" above.
  hero__image: "/images/geoffrey-sperl.jpg"